'use client';

import { Pencil, PenLine, Search, Sparkles } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/Button';

import { TextAreaField } from '@/components/ui/TextAreaField';
import { aiConfig } from '@/config/ai';
import {
  useEpisodeForecast,
  useRefineIdea,
  useRerunResearch,
  useWriteIdea,
} from '@/hooks/queries';
import { combineForecasts } from '@/lib/cost-forecast';
import { blockedReason } from '@/lib/provider-readiness';
import type { EpisodeStageVO } from '@/types/value-objects';

import { RunDialog } from './RunDialog';
import { StagePanel } from './StagePanel';

export interface IdeaPanelProps {
  episodeId: string;
}

function ideaOf(output: Record<string, unknown> | null): string {
  return typeof output?.['idea'] === 'string' ? output['idea'] : '';
}

/** Set by `ideaNode` from the `ideaMode` channel — a run that revised, rather than rewrote. */
function wasRefined(output: Record<string, unknown> | null): boolean {
  return output?.['mode'] === 'refine';
}

/**
 * The episode's idea — generated by the pipeline or typed here, the two are the same field. Writing
 * it by hand on a PENDING stage flips it to Ready, so Approve carries on to the script from either
 * starting point.
 *
 * Four ways to change it, and the distinction between them is the reason they are four buttons:
 *
 * - **Edit** — you type it. No model, no cost.
 * - **Refine** — improve *this* idea. Keeps premise, cast and ending.
 * - **Regenerate** (from `StagePanel`) — a different idea from the same research.
 * - **Re-research** — search again, then write a new idea from what came back.
 *
 * Regenerate used to be all three of the last ones at once: it re-ran `ideaPrompt`, which never
 * receives the current idea, so "make the ending land harder" quietly produced a different episode.
 */
export function IdeaPanel({ episodeId }: IdeaPanelProps) {
  const writeIdea = useWriteIdea(episodeId);
  const refineIdea = useRefineIdea(episodeId);
  const rerunResearch = useRerunResearch(episodeId);
  const { data: forecast } = useEpisodeForecast(episodeId);
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [openDialog, setOpenDialog] = useState<'refine' | 'research' | null>(null);
  const [refineNote, setRefineNote] = useState('');
  const [researchNote, setResearchNote] = useState('');

  function startEditing(idea: string) {
    setDraft(idea);
    setError(null);
    setIsEditing(true);
  }

  function save() {
    writeIdea.mutate(draft, {
      onSuccess: (result) => {
        setError(result.message ?? null);
        setIsEditing(false);
      },
    });
  }

  const ideaForecast = forecast?.stages.IDEA;
  const researchForecast = forecast?.stages.RESEARCH;
  // Re-research bills both stages on one click, so it quotes both — see `combineForecasts`.
  const rerunForecast =
    researchForecast && ideaForecast ? combineForecasts(researchForecast, ideaForecast) : undefined;

  // Refine re-runs IDEA and Re-research re-runs RESEARCH first, so each is gated by the credentials
  // of the stage it actually starts — the same asymmetry `StagePanel` applies to Approve.
  const ideaBlocked = blockedReason(forecast?.readiness.stages.IDEA);
  const researchBlocked = blockedReason(forecast?.readiness.stages.RESEARCH) ?? ideaBlocked;

  return (
    <StagePanel
      episodeId={episodeId}
      kind="IDEA"
      upstreamLabel="Research"
      emptyAction={() =>
        isEditing ? null : (
          <Button size="sm" variant="outline" onClick={() => startEditing('')}>
            <PenLine aria-hidden="true" />
            Write the idea yourself
          </Button>
        )
      }
      /*
       * Buttons *and* their dialogs live here rather than in `children`. `StagePanel` renders
       * `children` only for a stage that is neither GENERATING nor FAILED, but it renders `actions`
       * for READY / FAILED / APPROVED — so a dialog mounted from `children` would be missing in
       * exactly the FAILED state where its button is still on screen, and the click would silently
       * do nothing. Radix portals the dialog out of the footer, so nesting it here costs nothing.
       */
      actions={(stage: EpisodeStageVO) => {
        // Refine and Regenerate share one `attempt` counter, because they are the same stage re-run.
        const isCapped = stage.attempt >= aiConfig.limits.maxRegenPerStage;
        const hasIdea = Boolean(ideaOf(stage.output));

        return (
          <>
            <Button
              size="sm"
              variant="outline"
              isLoading={refineIdea.isPending}
              disabled={refineIdea.isPending || isCapped || !hasIdea || Boolean(ideaBlocked)}
              title={ideaBlocked ?? (hasIdea ? undefined : 'Nothing to refine yet')}
              onClick={() => setOpenDialog('refine')}
            >
              {refineIdea.isPending ? null : <Sparkles aria-hidden="true" />}
              {refineIdea.isPending ? 'Refining…' : 'Refine'}
            </Button>
            <Button
              size="sm"
              variant="outline"
              isLoading={rerunResearch.isPending}
              disabled={rerunResearch.isPending || isCapped || Boolean(researchBlocked)}
              title={researchBlocked ?? undefined}
              onClick={() => setOpenDialog('research')}
            >
              {rerunResearch.isPending ? null : <Search aria-hidden="true" />}
              {rerunResearch.isPending ? 'Researching…' : 'Re-research'}
            </Button>

            <RunDialog
              isOpen={openDialog === 'refine'}
              onOpenChange={(open) => setOpenDialog(open ? 'refine' : null)}
              title="Refine this idea?"
              description="Improves the idea that is there — the premise, the cast and the ending stay as they are, and the note below is what changes. To get a different episode entirely, use Regenerate instead."
              {...(ideaForecast ? { forecast: ideaForecast } : {})}
              note={{
                value: refineNote,
                onChange: setRefineNote,
                placeholder: 'e.g. "make the ending land harder", "give Luna more to lose"',
              }}
              confirmLabel="Refine"
              pendingLabel="Refining…"
              isPending={refineIdea.isPending}
              onConfirm={() => {
                setError(null);
                refineIdea.mutate(refineNote || undefined, {
                  onSuccess: (result) => setError(result.message ?? null),
                  onSettled: () => {
                    setRefineNote('');
                    setOpenDialog(null);
                  },
                });
              }}
            />

            <RunDialog
              isOpen={openDialog === 'research'}
              onOpenChange={(open) => setOpenDialog(open ? 'research' : null)}
              title="Research again and rewrite the idea?"
              description="Runs the research stage from scratch, then writes a new idea from what it finds. This replaces both — the current idea is not kept. It is the most expensive of the three."
              {...(rerunForecast ? { forecast: rerunForecast } : {})}
              note={{
                value: researchNote,
                onChange: setResearchNote,
                placeholder: 'Steers the new idea, not the search — e.g. "lean into the archive angle"',
              }}
              confirmLabel="Re-research & rewrite"
              pendingLabel="Starting…"
              isPending={rerunResearch.isPending}
              isDanger
              onConfirm={() => {
                setError(null);
                rerunResearch.mutate(researchNote || undefined, {
                  onSuccess: (result) => setError(result.message ?? null),
                  onSettled: () => {
                    setResearchNote('');
                    setOpenDialog(null);
                  },
                });
              }}
            />
          </>
        );
      }}
    >
      {(stage: EpisodeStageVO) => {
        const idea = ideaOf(stage.output);

        if (isEditing) {
          return (
            <div className="flex flex-col gap-3">
              <TextAreaField
                label="Idea"
                value={draft}
                onChange={setDraft}
                rows={8}
                placeholder="What happens in this episode? A paragraph is plenty — the script is written from it."
              />
              <div className="flex flex-wrap gap-2">
                <Button
                  size="sm"
                  isLoading={writeIdea.isPending}
                  disabled={writeIdea.isPending || !draft.trim()}
                  onClick={save}
                >
                  {writeIdea.isPending ? 'Saving…' : 'Save idea'}
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  disabled={writeIdea.isPending}
                  onClick={() => setIsEditing(false)}
                >
                  Cancel
                </Button>
              </div>
            </div>
          );
        }

        return (
          <div className="flex flex-col gap-3">
            {idea ? (
              <p className="text-foreground text-sm leading-relaxed whitespace-pre-line">{idea}</p>
            ) : stage.status === 'PENDING' ? null : (
              <p className="text-foreground-subtle text-sm">Nothing generated yet.</p>
            )}
            {wasRefined(stage.output) ? (
              <p className="text-foreground-subtle text-xs">Revised from the previous version.</p>
            ) : null}
            {error ? <p className="text-destructive-text text-xs">{error}</p> : null}
            {idea ? (
              <div>
                <Button size="sm" variant="ghost" onClick={() => startEditing(idea)}>
                  <Pencil aria-hidden="true" />
                  Edit idea
                </Button>
              </div>
            ) : null}
          </div>
        );
      }}
    </StagePanel>
  );
}
IdeaPanel.displayName = 'IdeaPanel';
